# PostgreSQL database configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("DATABASE_URL") %>

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV.fetch("TEST_DATABASE_URL") { "postgresql://localhost/withdui_test?pool=5" } %>
  database: withdui_test
  # Mac Tahoe bug
  gssencmode: disable

production:
  <<: *default
